article/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-14 22:28:12
# @Author  : warlock921 (caoyu921@163.com)
# @Link    : http://www.thinkheh.cn
# @Version : $Id$

from django.conf.urls import url 
from . import views,list_views

urlpatterns = [
	url(r'^article-column/$', views.article_column, name='article_column'),
	url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
	url(r'^del-column/$', views.del_article_column, name='del_article_column'),
	url(r'^article-post/$', views.article_post, name='article_post'),
	url(r'^article-list/$', views.article_list, name='article_list'),
	url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
	url(r'^del-article/$', views.del_article, name="del_article"),
	url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
	url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
	url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
	url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
	url(r'^image-upload/$', views.editor_image_upload, name='editor_image_upload'),
	url(r'^like-article/$', list_views.like_article, name="like_article"),
	url(r'^article-tag/$', views.article_tag, name="article_tag"),
	url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),

] 

course/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-01-23 16:40:41
# @Author  : warlock921 (caoyu921@163.com)
# @Link    : http://www.thinkheh.cn
# @Version : $Id$

from django.conf.urls import url
from .views import AboutView,CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView

urlpatterns = [
	url(r'about/$',AboutView.as_view(),name="about"),
	url(r'course-list/$',CourseListView.as_view(),name="course_list"),
	url(r'manage-course/$',ManageCourseListView.as_view(),name="manage_course"),
	url(r'create-course/$', CreateCourseView.as_view(), name="create_course"),
	url(r'delete-course/(?P<pk>\d+)/$', DeleteCourseView.as_view(), name="delete_course"),
]

thinkheh/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainsite/', include('mainsite.urls', namespace='mainsite', app_name='mainsite')),
    url(r'^account/',include('account.urls', namespace='account', app_name='account')),
    url(r'^article/',include('article.urls', namespace='article', app_name='article')),
    url(r'^imageload/',include('imageload.urls', namespace='imageload', app_name='imageload')),
    url(r'^course/',include('course.urls',namespace='course', app_name='course')),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.utils import timezone
from django.core.urlresolvers import reverse
from slugify import slugify

#栏目设置数据库模型
class AriticleColumn(models.Model):
	user = models.ForeignKey(User,verbose_name='创建者', related_name = 'article_column')
	column = models.CharField(verbose_name='私有栏目名称',max_length=200)
	created = models.DateField(verbose_name='创建日期',auto_now_add=True)

	def __str__(self):
		return self.column

	class Meta:
		verbose_name = "私有栏目管理"
		verbose_name_plural = "私有栏目管理"

#问题标签---注意：这个类必须放在AriticlePost的前面
class ArticleTag(models.Model):
	author = models.ForeignKey(User,verbose_name="用户名", related_name="tag")
	tag = models.CharField(verbose_name="问题标签", max_length=24)

	def __str__(self):
		return self.tag

	class Meta:
		verbose_name = "问题标签管理"
		verbose_name_plural = "问题标签管理"

#问答主题发布-数据库模型
class AriticlePost(models.Model):
	author = models.ForeignKey(User,verbose_name="作者",related_name="article")
	title = models.CharField(verbose_name="话题名称", max_length=200)
	#重要的标志
	slug = models.SlugField(verbose_name="地址", max_length=500)
	column = models.ForeignKey(AriticleColumn, verbose_name="话题栏目名称", related_name="article_column")
	body = models.TextField(verbose_name="话题内容")
	created = models.DateTimeField(verbose_name="创建日期", default=timezone.now)
	updated = models.DateTimeField(verbose_name="更新日期", auto_now=True)
	users_like = models.ManyToManyField(User,verbose_name="点赞数", related_name="articles_like", blank=True)
	article_tag = models.ManyToManyField(ArticleTag,verbose_name="问题标签", related_name='article_tag', blank=True)
	
	class Meta:
		ordering = ("-updated",)
		index_together = (('id','slug'),)
		verbose_name = "问题主题内容管理"
		verbose_name_plural = "问题主题内容管理"

	def __str__(self):
		return self.title

	def save(self,*args, **kargs):
		self.slug = slugify(self.title)
		super(AriticlePost,self).save(*args, **kargs)

	def get_absolute_url(self):
		return reverse("article:article_detail", args=[self.id,self.slug])

	def get_url_path(self):
		return reverse("article:list_article_detail", args=[self.id,self.slug])

#问题评论或答案发布-数据库模型
class Comment(models.Model):
	article = models.ForeignKey(AriticlePost,verbose_name="问题外键", related_name="comments")
	commentator = models.CharField(verbose_name="回答问题的人",max_length=90)
	body = models.TextField(verbose_name="答案的内容")
	created = models.DateTimeField(verbose_name="答案创建时间", auto_now_add=True)
	#is_best_answer = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created',)
		verbose_name = "问题答案管理"
		verbose_name_plural = "问题答案管理"

	def __str__(self):
		return "Comment by {0} on {1}".format(self.commentator,self.article)



		

article/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-14 22:13:31
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django import forms 
from .models import AriticleColumn,AriticlePost,Comment,ArticleTag

#问题标签表单
class AriticleColumnForm(forms.ModelForm):
	class Meta:
		model = AriticleColumn 
		fields = ("column",)

#问题提交表单
class AriticlePostForm(forms.ModelForm):
	class Meta:
		model = AriticlePost
		fields = ("title", "body")

#评论提交表单
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment 
		fields = ("body",)

#问题标签表单
class ArticleTagForm(forms.ModelForm):
	class Meta:
		model = ArticleTag 
		fields = ('tag',)


		
		

article/views.py
import json
import os
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.utils import timezone
from django.conf import settings
#from slugify import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

from .forms import AriticleColumnForm,AriticlePostForm,ArticleTagForm
from .models import AriticleColumn,AriticlePost,ArticleTag

from actions.utils import create_action

import json

#话题标签视图
@login_required(login_url='/account/login')
@csrf_exempt
def article_column(request):
	if request.method == "GET":
		columns = AriticleColumn.objects.filter(user=request.user)
		column_form = AriticleColumnForm()
		return render(request, "article/column/article_column.html", {"columns":columns,'column_form':column_form})

	if request.method == "POST":
		column_name = request.POST['column']
		columns = AriticleColumn.objects.filter(user_id=request.user.id,column=column_name)
		#取得当前用户的所有栏目结果集
		columns_re = AriticleColumn.objects.filter(user=request.user)
		if columns:
			return HttpResponse('2')
		#判断是否超过5个(含5个)标签
		elif(columns_re.count()>=5):
			return HttpResponse('3')
		else:
			AriticleColumn.objects.create(user=request.user, column=column_name)
			return HttpResponse("1")

#重命名话题标签视图
@login_required(login_url='/account/login')
@require_POST       #这里表示只接受POST事件
@csrf_exempt
def rename_article_column(request):
	column_name = request.POST["column_name"]
	column_id = request.POST['column_id']
	try:
		line = AriticleColumn.objects.get(id=column_id)
		line.column = column_name
		line.save()
		return HttpResponse("1")
	except:
		return HttpResponse("0")

#删除话题标签视图
@login_required(login_url='/account/login')
@require_POST       #这里表示只接受POST事件
@csrf_exempt
def del_article_column(request):
	column_id = request.POST['column_id']
	try:
		line = AriticleColumn.objects.get(id=column_id)
		line.delete()
		return HttpResponse("1")
	except:
		return HttpResponse("2")

#发布话题视图
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
	tag_list = ArticleTag.objects.filter(author=request.user)
	#print(tag_list)
	if request.method == "POST":
		article_post_form = AriticlePostForm(data=request.POST)
		if article_post_form.is_valid():
			cd = article_post_form.cleaned_data
			try:
				new_article = article_post_form.save(commit=False)
				new_article.author = request.user
				new_article.column = request.user.article_column.get(id=request.POST['column_id'])
				new_article.save()
				#记录用户动作
				create_action(request.user, '发布了话题：', new_article)

				tags = request.POST['tags']
				if tags:
					for atag in json.loads(tags):
						tag = request.user.tag.get(tag=atag) 
						new_article.article_tag.add(tag)

				return HttpResponse("1")
			except Exception as e:
				return HttpResponse("2")
		else:
			return HttpResponse("3")
	else:
		article_post_form = AriticlePostForm()
		article_columns = request.user.article_column.all()
		#article_tags = request.user.tag.all()
		return render(request, "article/column/article_post.html", {"article_post_form":article_post_form, "article_columns":article_columns, "tag_list":tag_list})

#已发布话题列表视图
@login_required(login_url='/account/login')
def article_list(request):
	articles_list = AriticlePost.objects.filter(author=request.user)
	paginator = Paginator(articles_list,5)
	page = request.GET.get('page')
	try:
		current_page = paginator.page(page)
		articles = current_page.object_list
	except PageNotAnInteger:
		current_page = paginator.page(1)
		articles = current_page.object_list
	except EmptyPage:
		current_page = paginator.page(paginator.num_pages)
		articles = current_page.object_list
	return render(request, "article/column/article_list.html", {"articles":articles, "page":current_page})

#显示话题正文视图
@login_required(login_url='/account/login')
def article_detail(request,id,slug):
	article = get_object_or_404(AriticlePost, id=id, slug=slug)
	return render(request, "article/column/article_detail.html", {"article":article})

#删除话题视图
@login_required(login_url='/account/login')
@require_POST   #这里表示只接受POST事件
@csrf_exempt
def del_article(request):
	article_id = request.POST['article_id']
	try:
		article = AriticlePost.objects.get(id=article_id)
		article.delete()
		#记录用户动作
		create_action(request.user, '删除了话题：', article)
		return HttpResponse("1")
	except Exception as e:
		return HttpResponse("2")

#编辑话题视图
@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request,article_id):
	if request.method == "GET":
		article_columns = request.user.article_column.all()
		article = AriticlePost.objects.get(id=article_id)
		this_article_form = AriticlePostForm(initial={"title":article.title})
		this_article_column = article_column
		return render(request, "article/column/redit_article.html", {"article":article, "article_columns":article_columns, "this_article_column":this_article_column, "this_article_form":this_article_form})

	else:
		redit_article = AriticlePost.objects.get(id=article_id)
		try:
			redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
			redit_article.title = request.POST['title']
			redit_article.body = request.POST['body']
			redit_article.save()
			#记录用户动作
			create_action(request.user, '修改了话题：', redit_article)
			return HttpResponse("1")
		except Exception as e:
			return HttpResponse("2")

#富文本编辑器图片上传处理
@login_required(login_url='/account/login')
@require_POST   #这里表示只接受POST事件
@csrf_exempt
def editor_image_upload(request):
	response_data = {}
	if request.method == "POST":
		upload_image_file = request.FILES.get('editormd-image-file')
		#print(upload_image_file.name,upload_image_file.size)
		#取文件的扩展名
		file_ext = os.path.splitext(upload_image_file.name)[1]
		new_upload_image_file = timezone.now().strftime('%Y%m%d%H%M%S') + file_ext
		#print(new_upload_image_file)
		if not upload_image_file:
			response_data['success'] = 0
			response_data['message'] = u'图片格式异常'
			return HttpResponse(json.dumps(response_data),content_type="application/json")
		else:
			if upload_image_file.size < 5242880 :
				#按年和按日期建立图片文件夹，文件夹不存在，会自动创建
				up_year = timezone.now().strftime('%Y')
				up_date = timezone.now().strftime('%m')+"-"+timezone.now().strftime('%d')
				#组装图片路径并上传图片至服务器
				img_url = default_storage.save("editor_images"+"/"+request.user.username+"/"+up_year+"/"+up_date+"/"+new_upload_image_file,ContentFile(upload_image_file.read()))
				# tmp_file = os.path.join(settings.MEDIA_ROOT,img_url).replace('\\','/')	  #调试信息
				# upload_image_file.save(os.path.join(settings.BASE_DIR,'static/editor_up_load/%Y/%m/%d',new_upload_image_file))
				# print(img_url)  #调试信息
				# print(tmp_file)  #调试信息
				response_data['success'] = 1
				response_data['message'] = u'上传成功'
				#这里非常重要，路径一定不能修改，否则无法正常显示图片
				response_data['url'] = '/static/image_upload/'+img_url
				#response_data = {'success':1,'message':"上传成功",'url':'http://www.thinkheh.cn'}  ----样例
				return HttpResponse(json.dumps(response_data),content_type="application/json")
			else:
				response_data['success'] = 0
				response_data['message'] = u'图片大小超过 5 Mb'
				return HttpResponse(json.dumps(response_data),content_type="application/json")

#问题标签视图函数
@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
	if request.method == "GET":
		article_tags = ArticleTag.objects.filter(author=request.user)
		article_tag_form = ArticleTagForm()
		return render(request, "article/tag/tag_list.html", {"article_tags":article_tags, "article_tag_form":article_tag_form})

	if request.method == "POST":
		#取得用户输入的tag名称
		tag_name = request.POST['tag']
		#从数据库中筛选与当前author_id、tag相同的记录
		tags = ArticleTag.objects.filter(author_id=request.user.id,tag=tag_name)
		#从数据库中筛选当前用户的所有tag
		tag_re = ArticleTag.objects.filter(author=request.user)

		#首先判断tag是否存在
		if tags:
			return HttpResponse('标签名称已存在，请重新更换标签名称！')
		#如果tag不存在，就判断用户的tag数量是否超过10个（含10个），超出则不允许再创建
		elif(tag_re.count()>=10):
			return HttpResponse('标签数量超过10个，无法再添加！')
		#如果前两个条件均不满足，则创建新tag
		else:
			#下面是创建tag的过程
			tag_post_form = ArticleTagForm(data=request.POST)
			print(tag_re)
			if tag_post_form.is_valid():
				print("表单验证通过！")
				try:
					new_tag = tag_post_form.save(commit=False)
					new_tag.author = request.user
					new_tag.save()
					return HttpResponse("1")
				except Exception as e:
					print(e)
					return HttpResponse("数据保存失败")
				else:
					return HttpResponse("对不起，表单验证失败！")

#删除话题标签视图
@login_required(login_url='/account/login')
@require_POST   #这里表示只接受POST事件
@csrf_exempt
def del_article_tag(request):
	tag_id = request.POST['tag_id']
	try:
		tag = ArticleTag.objects.get(id=tag_id)
		tag.delete()
		return HttpResponse("1")
	except Exception as e:
		print(e)
		return HttpResponse("2")

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}
    话题管理
{% endblock title %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'editor/css/editormd.css' %}">
    <div style="margin-left: 10px">
    	<form class="form-horizontal" action="." method="post">{% csrf_token %}
    		<div class="row" style="margin-top: 10px;">
    			<div class="col-md-2 text-right"><span>标题：</span></div>
    			<div class="col-md-10 text-left">{{article_post_form.title}}</div>
    		</div>
    		<div class="row" style="margin-top: 10px">
    			<div class="col-md-2 text-right"><span>私有栏目名称：</span></div>
    			<div class="col-md-10 text-left">
    				<select id="which_column">
    					{% for column in article_columns %}
    						<option value="{{column.id}}">{{column.column}}</option>
    					{% endfor %}
    				</select>
    			</div>
    		</div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>问题标签：</span></div>
                <div class="col-md-10 text-left">
                    {% for tag in tag_list %}
                        <label class="checkbox-inline">
                            <input class="tagcheckbox" id="{{ tag.id }}" name="article_tag" type="checkbox" value="{{ tag.tag }}" />{{ tag.tag }}
                        </label>
                    {% empty %}
                    <p>你还没有任何标签,请 <a href="{% url 'article:article_tag' %}">添加标签</a></p>
                    {% endfor %}
                </div>
            </div>
    		<div class="row" style="margin-top: 10px">
    			<div class="col-md-2 text-right"><span>内容：</span></div>
    			<div id="editormd" class="col-md-10 text-left">
    				<textarea style="display: none;" id="id_body"></textarea>
    			</div>
    		</div>
    		<div class="row">
                <div class="col-md-2 text-right"><span></span></div>
    			<input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
    		</div>
    	</form>
    </div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
<script type="text/javascript">
	function publish_article(){
		var title = $("#id_title").val();
		var column_id = $("#which_column").val();
		var body = $("#id_body").val();
        var article_tags = [];
        $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});
		$.ajax({
			url:"{% url 'article:article_post' %}",
			type:"POST",
			data:{"title":title, "body":body, "column_id":column_id, "tags":JSON.stringify(article_tags)},
			success:function(e){
				if(e=="1"){
					layer.msg("成功发布话题");
					location.href = "{% url 'article:article_list' %}";
				}else if(e=="2"){
					layer.msg("对不起，话题发布失败！");
				}else{
					layer.msg("话题名称和话题标签不能为空！")
				}
			}
		});
	}

	//简单的 Markdown 编辑器
	$(function(){
		var editor = editormd("editormd", {
			// width  : "100%",
			// height : 640,
			// emoji:true,
			// imageUpload : true,
			// imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
			// imageUploadURL : "{% static 'editor_up_load/images' %}",
			// syncScrolling:"single",
			// path :"{% static 'editor/lib/' %}"
                width   : "80%",
                height  : 500,
                //syncScrolling : "single",
                path    : "{% static 'editor/lib/' %}",
                saveHTMLToTextarea : true,

                emoji: true,//emoji表情，默认关闭
                taskList: true,
                tocm: true, // Using [TOCM]
                tex: true,// 开启科学公式TeX语言支持，默认关闭

                flowChart: true,//开启流程图支持，默认关闭
                sequenceDiagram: true,//开启时序/序列图支持，默认关闭,

                dialogLockScreen : false,//设置弹出层对话框不锁屏，全局通用，默认为true
                dialogShowMask : false,//设置弹出层对话框显示透明遮罩层，全局通用，默认为true
                dialogDraggable : false,//设置弹出层对话框不可拖动，全局通用，默认为true
                dialogMaskOpacity : 0.4, //设置透明遮罩层的透明度，全局通用，默认值为0.1
                dialogMaskBgColor : "#000",//设置透明遮罩层的背景颜色，全局通用，默认为#fff

                codeFold: true,

                imageUpload : true,
                imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                imageUploadURL : "{% url 'article:editor_image_upload' %}",

                /*上传图片成功后可以做一些自己的处理*/
                // onload: function () {
                //     //console.log('onload', this);
                //     //this.fullscreen();
                //     //this.unwatch();
                //     //this.watch().fullscreen();
                //     //this.width("100%");
                //     //this.height(480);
                //     //this.resize("100%", 640);
                // },

                /**设置主题颜色*/
                editorTheme: "pastel-on-dark",
                theme: "-midnight",
                previewTheme: "midnight"
             });
	});

</script>
{% endblock content %}

templates/article/column/redit_article.html
{% extends "article/base.html" %}

{% load staticfiles %}

{% block title %}
    话题内容修改
{% endblock title %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'editor/css/editormd.css' %}">
    <div style="margin-left: 10px">
    	<form class="form-horizontal" action="." method="post">{% csrf_token %}
    		<div class="row" style="margin-top: 10px;">
    			<div class="col-md-2 text-right"><span>标题：</span></div>
    			<div class="col-md-10 text-left">{{this_article_form.title}}</div>
    		</div>
    		<div class="row" style="margin-top: 10px">
    			<div class="col-md-2 text-right"><span>私有栏目名称：</span></div>
    			<div class="col-md-10 text-left">
    				<select id="which_column">
    					{% for column in article_columns %}
    						{% if column == this_article_column.column %}
    						    <option value="{{column.id}}" selected="selected">{{column.column}}</option>
    						{% else %}
    						    <option value="{{column.id}}">{{column.column}}</option>
    						{% endif %}
    					{% endfor %}
    				</select>
    			</div>
    		</div>
            <div class="row" style="margin-top: 10px">
                <div class="col-md-2 text-right"><span>问题标签：</span></div>
                <div class="col-md-10 text-left">
                   {{ article.article_tag.all | join:", " }}
                </div>
            </div>
    		<div class="row" style="margin-top: 10px">
    			<div class="col-md-2 text-right"><span>内容：</span></div>
    			<div id="editormd" class="col-md-10 text-left">
    				<textarea style="display: none;" id="id_body">{{article.body}}</textarea>
    			</div>
    		</div>
    		<div class="row">
                    <div class="col-md-2 text-right"><span></span></div>
    			<input type="button" class="btn btn-primary btn-lg" value="提交修改" onclick="redit_article()">
    		</div>
    	</form>
    </div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
<script type="text/javascript">
	function redit_article(){
		var title = $("#id_title").val();
		var column_id = $("#which_column").val();
		var body = $("#id_body").val();
		$.ajax({
			url:"{% url 'article:redit_article' article.id %}",
			type:"POST",
			data:{"title":title, "body":body, "column_id":column_id},
			success:function(e){
				if(e=="1"){
					layer.msg("话题修改成功！");
					location.href = "{% url 'article:article_list' %}";
				}else if(e=="2"){
					layer.msg("对不起，话题修改失败！");
				}else{
					layer.msg("话题名称必须写,不能空！")
				}
			}
		});
	}

	//简单的 Markdown 编辑器
	$(function(){
		var editor = editormd("editormd", {
			// width  : "100%",
			// height : 640,
			// emoji:true,
			// imageUpload : true,
			// imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
			// imageUploadURL : "{% static 'editor_up_load/images' %}",
			// syncScrolling:"single",
			// path :"{% static 'editor/lib/' %}"
                width   : "80%",
                height  : 500,
                //syncScrolling : "single",
                path    : "{% static 'editor/lib/' %}",
                saveHTMLToTextarea : true,

                emoji: true,//emoji表情，默认关闭
                taskList: true,
                tocm: true, // Using [TOCM]
                tex: true,// 开启科学公式TeX语言支持，默认关闭

                flowChart: true,//开启流程图支持，默认关闭
                sequenceDiagram: true,//开启时序/序列图支持，默认关闭,

                dialogLockScreen : false,//设置弹出层对话框不锁屏，全局通用，默认为true
                dialogShowMask : false,//设置弹出层对话框显示透明遮罩层，全局通用，默认为true
                dialogDraggable : false,//设置弹出层对话框不可拖动，全局通用，默认为true
                dialogMaskOpacity : 0.4, //设置透明遮罩层的透明度，全局通用，默认值为0.1
                dialogMaskBgColor : "#000",//设置透明遮罩层的背景颜色，全局通用，默认为#fff

                codeFold: true,

                imageUpload : true,
                imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                imageUploadURL : "{% url 'article:editor_image_upload' %}",

                /*上传图片成功后可以做一些自己的处理*/
                // onload: function () {
                //     //console.log('onload', this);
                //     //this.fullscreen();
                //     //this.unwatch();
                //     //this.watch().fullscreen();
                //     //this.width("100%");
                //     //this.height(480);
                //     //this.resize("100%", 640);
                // },

                /**设置主题颜色*/
                editorTheme: "pastel-on-dark",
                theme: "-midnight",
                previewTheme: "midnight"
             });
	});

</script>
{% endblock content %}