account/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-09 19:15:54
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django.conf.urls import url 
from . import views
from django.conf import settings 
from django.contrib.auth import views as auth_views

urlpatterns = [
	#url(r'^login/$', views.user_login, name="user_login"),
	url(r'^login/$', auth_views.login, name="user_login"),
	#url(r'^new-login/$', auth_views.login, {"template_name":"account/login.html"}),
	url(r'^logout/$', auth_views.logout, {"template_name":"account/logout.html"}, name="user_logout"),
	url(r'^register/$',views.register,name="user_register"),
	url(r'^password-change/$', auth_views.password_change, {"post_change_redirect":"/account/password-change-done"}, name='password_change'),
	url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
	url(r'^password-reset/$', auth_views.password_reset,{"template_name":"account/password_reset_form.html","email_template_name":"account/password_reset_email.html","subject_template_name":"account/password_reset_subject.txt","post_reset_redirect":"/account/password-reset-done"},name="password_reset"),
	url(r'^password-reset-done/$', auth_views.password_reset_done, {"template_name":"account/password_reset_done.html"}, name="password_reset_done"),
	url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {"template_name":"account/password_reset_confirm.html","post_reset_redirect":"/account/password-reset-complete"}, name="password_reset_confirm"),
	url(r'^password-reset-complete/$', auth_views.password_reset_complete, {"template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
	url(r'^my-info/$', views.myself, name="my_info"),
	url(r'^edit-my-info/$', views.myself_edit, name="edit_my_info"),
	url(r'^my-image/$',views.my_image, name="my_image"),
	url(r'^users/$', views.user_list, name="user_list"),
	url(r'^users/follow/$', views.user_follow, name='user_follow'),
	url(r'^users/(?P<username>[-\w]+)/$', views.user_detail, name="user_detail"),

]

article/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-14 22:28:12
# @Author  : warlock921 (caoyu921@163.com)
# @Link    : http://www.thinkheh.cn
# @Version : $Id$

from django.conf.urls import url 
from . import views,list_views

urlpatterns = [
	url(r'^article-column/$', views.article_column, name='article_column'),
	url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
	url(r'^del-column/$', views.del_article_column, name='del_article_column'),
	url(r'^article-post/$', views.article_post, name='article_post'),
	url(r'^article-list/$', views.article_list, name='article_list'),
	url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
	url(r'^del-article/$', views.del_article, name="del_article"),
	url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
	url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
	url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
	url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
	url(r'^image-upload/$', views.editor_image_upload, name='editor_image_upload'),
	url(r'^like-article/$', list_views.like_article, name="like_article"),
	url(r'^article-tag/$', views.article_tag, name="article_tag"),
	url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),

] 

course/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-01-23 16:40:41
# @Author  : warlock921 (caoyu921@163.com)
# @Link    : http://www.thinkheh.cn
# @Version : $Id$

from django.conf.urls import url
from .views import AboutView,CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView

urlpatterns = [
	url(r'about/$',AboutView.as_view(),name="about"),
	url(r'course-list/$',CourseListView.as_view(),name="course_list"),
	url(r'manage-course/$',ManageCourseListView.as_view(),name="manage_course"),
	url(r'create-course/$', CreateCourseView.as_view(), name="create_course"),
	url(r'delete-course/(?P<pk>\d+)/$', DeleteCourseView.as_view(), name="delete_course"),
]

mainsite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-07 21:12:12
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.mainsite_title, name="mainsite_title"),
	url(r'^(?P<article_id>\d)/$',views.mainsite_article,name="mainsite_detail")
]

thinkheh/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainsite/', include('mainsite.urls', namespace='mainsite', app_name='mainsite')),
    url(r'^account/',include('account.urls', namespace='account', app_name='account')),
    url(r'^article/',include('article.urls', namespace='article', app_name='article')),
    url(r'^imageload/',include('imageload.urls', namespace='imageload', app_name='imageload')),
    url(r'^course/',include('course.urls',namespace='course', app_name='course')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">

</head>
<body>
	{% include "header.html" %}
	<div class="container">
	{% block content %}{% endblock content %}
</div>
{% include "footer.html" %}
	<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static '/js/bootstrap.js' %}"></script>
</body>
</html>

templates/footer.html
<footer class="footer" style="padding: inherit;">
	<hr>
	<div class="container">
		<p>&copy; By warlock921 {% now "Y" %}</p>
	</div>
</footer>

templates/header.html
{% load staticfiles %}

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav" role="navigation">
        <li><a class="navbar-brand" href="{% url 'mainsite:mainsite_title' %}">首页</a></li>
        <li><a class="navbar-brand" href="{% url 'article:article_titles' %}">问答</a></li>
        <li><a class="navbar-brand" href="{% url 'account:user_list' %}">用户</a></li>
        <li><a class="navbar-brand" href="{% url 'course:course_list' %}">视频新闻</a></li>
        <li><a class="navbar-brand" href="{% url 'course:about' %}">关于本站</a></li>
      </ul>
    </div>
    <div id="navbar" class="navbar-collapse collapse navbar-right">
      <div class="navbar-form navbar-right">
        {% if user.is_authenticated %}
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }} {% if user.is_superuser %}超级管理员{% endif %}<span class="caret"></span></button>
            <ul class="dropdown-menu">
              {% if userprofile.company_or_person == None %}
              <li><a href="{% url 'account:my_info' %}">信息中心</a></li>
              {% else %}
                  <!-- <li><a href="{% url 'account:my_info' %}">{{ userprofile.company_or_person }}信息</a></li> -->
              {% endif %}
              {% if user.is_superuser %}
              <li><a href="/admin">管理后台</a></li>
              {% endif %}
              <li><a href="{% url 'article:article_column' %}">内容管理</a></li>
              <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
              <li><a href="{% url 'account:password_reset' %}">忘记密码</a></li>
              <li><a href="{% url 'account:user_logout' %}">注销</a></li>
            </ul>
          </div>
        {% else %}
          <a href="{% url 'account:user_login' %}" class="btn btn-success" role="button">登录</a>
          <a href="{% url 'account:user_register' %}" class="btn btn-info" role="button">注册</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<!-- <script type="text/javascript" src="{% static '/js/bootstrap.js' %}"></script> -->

templates/paginator.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
		    <a href="?page={{ page.previous_page_number}}">上一页</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}
		</span>
		{% if page.has_next %}
		    <a href="?page={{ page.next_page_number}}">下一页</a>		
		{% endif %}
	</span>
</div>