account/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-09 19:15:54
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django.conf.urls import url 
from . import views
from django.conf import settings 
from django.contrib.auth import views as auth_views

urlpatterns = [
	#url(r'^login/$', views.user_login, name="user_login"),
	url(r'^login/$', auth_views.login, name="user_login"),
	#url(r'^new-login/$', auth_views.login, {"template_name":"account/login.html"}),
	url(r'^logout/$', auth_views.logout, {"template_name":"account/logout.html"}, name="user_logout"),
	url(r'^register/$',views.register,name="user_register"),
	url(r'^password-change/$', auth_views.password_change, {"post_change_redirect":"/account/password-change-done"}, name='password_change'),
	url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
	url(r'^password-reset/$', auth_views.password_reset,{"template_name":"account/password_reset_form.html","email_template_name":"account/password_reset_email.html","subject_template_name":"account/password_reset_subject.txt","post_reset_redirect":"/account/password-reset-done"},name="password_reset"),
	url(r'^password-reset-done/$', auth_views.password_reset_done, {"template_name":"account/password_reset_done.html"}, name="password_reset_done"),
	url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {"template_name":"account/password_reset_confirm.html","post_reset_redirect":"/account/password-reset-complete"}, name="password_reset_confirm"),
	url(r'^password-reset-complete/$', auth_views.password_reset_complete, {"template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
	url(r'^my-info/$', views.myself, name="my_info"),
	url(r'^edit-my-info/$', views.myself_edit, name="edit_my_info"),
	url(r'^my-image/$',views.my_image, name="my_image"),
	url(r'^users/$', views.user_list, name="user_list"),
	url(r'^users/follow/$', views.user_follow, name='user_follow'),
	url(r'^users/(?P<username>[-\w]+)/$', views.user_detail, name="user_detail"),

]

article/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-14 22:28:12
# @Author  : warlock921 (caoyu921@163.com)
# @Link    : http://www.thinkheh.cn
# @Version : $Id$

from django.conf.urls import url 
from . import views,list_views

urlpatterns = [
	url(r'^article-column/$', views.article_column, name='article_column'),
	url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
	url(r'^del-column/$', views.del_article_column, name='del_article_column'),
	url(r'^article-post/$', views.article_post, name='article_post'),
	url(r'^article-list/$', views.article_list, name='article_list'),
	url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
	url(r'^del-article/$', views.del_article, name="del_article"),
	url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
	url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
	url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
	url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
	url(r'^image-upload/$', views.editor_image_upload, name='editor_image_upload'),
	url(r'^like-article/$', list_views.like_article, name="like_article"),
	url(r'^article-tag/$', views.article_tag, name="article_tag"),
	url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),

] 

course/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-01-23 16:40:41
# @Author  : warlock921 (caoyu921@163.com)
# @Link    : http://www.thinkheh.cn
# @Version : $Id$

from django.conf.urls import url
from .views import AboutView,CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView

urlpatterns = [
	url(r'about/$',AboutView.as_view(),name="about"),
	url(r'course-list/$',CourseListView.as_view(),name="course_list"),
	url(r'manage-course/$',ManageCourseListView.as_view(),name="manage_course"),
	url(r'create-course/$', CreateCourseView.as_view(), name="create_course"),
	url(r'delete-course/(?P<pk>\d+)/$', DeleteCourseView.as_view(), name="delete_course"),
]

imageload/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-01-10 15:52:11
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^list-images/$', views.list_images, name='list_images'),
	url(r'^upload-image/$', views.upload_image, name='upload_image'),
	url(r'^upload-image-from-file/$', views.upload_image_from_file, name='upload_image_from_file'),
	url(r'^del-image/$', views.del_image, name='del_image'),
] 

mainsite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-07 21:12:12
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.mainsite_title, name="mainsite_title"),
	url(r'^(?P<article_id>\d)/$',views.mainsite_article,name="mainsite_detail")
]

thinkheh/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainsite/', include('mainsite.urls', namespace='mainsite', app_name='mainsite')),
    url(r'^account/',include('account.urls', namespace='account', app_name='account')),
    url(r'^article/',include('article.urls', namespace='article', app_name='article')),
    url(r'^imageload/',include('imageload.urls', namespace='imageload', app_name='imageload')),
    url(r'^course/',include('course.urls',namespace='course', app_name='course')),
]

article/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-12-14 22:13:31
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django import forms 
from .models import AriticleColumn,AriticlePost,Comment,ArticleTag

#问题标签表单
class AriticleColumnForm(forms.ModelForm):
	class Meta:
		model = AriticleColumn 
		fields = ("column",)

#问题提交表单
class AriticlePostForm(forms.ModelForm):
	class Meta:
		model = AriticlePost
		fields = ("title", "body")

#评论提交表单
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment 
		fields = ("body",)

#问题标签表单
class ArticleTagForm(forms.ModelForm):
	class Meta:
		model = ArticleTag 
		fields = ('tag',)


		
		

article/views.py
import json
import os
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.utils import timezone
from django.conf import settings
#from slugify import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

from .forms import AriticleColumnForm,AriticlePostForm,ArticleTagForm
from .models import AriticleColumn,AriticlePost,ArticleTag

from actions.utils import create_action

import json

#话题标签视图
@login_required(login_url='/account/login')
@csrf_exempt
def article_column(request):
	if request.method == "GET":
		columns = AriticleColumn.objects.filter(user=request.user)
		column_form = AriticleColumnForm()
		return render(request, "article/column/article_column.html", {"columns":columns,'column_form':column_form})

	if request.method == "POST":
		column_name = request.POST['column']
		columns = AriticleColumn.objects.filter(user_id=request.user.id,column=column_name)
		#取得当前用户的所有栏目结果集
		columns_re = AriticleColumn.objects.filter(user=request.user)
		if columns:
			return HttpResponse('2')
		#判断是否超过5个(含5个)标签
		elif(columns_re.count()>=5):
			return HttpResponse('3')
		else:
			AriticleColumn.objects.create(user=request.user, column=column_name)
			return HttpResponse("1")

#重命名话题标签视图
@login_required(login_url='/account/login')
@require_POST       #这里表示只接受POST事件
@csrf_exempt
def rename_article_column(request):
	column_name = request.POST["column_name"]
	column_id = request.POST['column_id']
	try:
		line = AriticleColumn.objects.get(id=column_id)
		line.column = column_name
		line.save()
		return HttpResponse("1")
	except:
		return HttpResponse("0")

#删除话题标签视图
@login_required(login_url='/account/login')
@require_POST       #这里表示只接受POST事件
@csrf_exempt
def del_article_column(request):
	column_id = request.POST['column_id']
	try:
		line = AriticleColumn.objects.get(id=column_id)
		line.delete()
		return HttpResponse("1")
	except:
		return HttpResponse("2")

#发布话题视图
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
	tag_list = ArticleTag.objects.filter(author=request.user)
	#print(tag_list)
	if request.method == "POST":
		article_post_form = AriticlePostForm(data=request.POST)
		if article_post_form.is_valid():
			cd = article_post_form.cleaned_data
			try:
				new_article = article_post_form.save(commit=False)
				new_article.author = request.user
				new_article.column = request.user.article_column.get(id=request.POST['column_id'])
				new_article.save()
				#记录用户动作
				create_action(request.user, '发布了话题：', new_article)

				tags = request.POST['tags']
				if tags:
					for atag in json.loads(tags):
						tag = request.user.tag.get(tag=atag) 
						new_article.article_tag.add(tag)

				return HttpResponse("1")
			except Exception as e:
				return HttpResponse("2")
		else:
			return HttpResponse("3")
	else:
		article_post_form = AriticlePostForm()
		article_columns = request.user.article_column.all()
		#article_tags = request.user.tag.all()
		return render(request, "article/column/article_post.html", {"article_post_form":article_post_form, "article_columns":article_columns, "tag_list":tag_list})

#已发布话题列表视图
@login_required(login_url='/account/login')
def article_list(request):
	articles_list = AriticlePost.objects.filter(author=request.user)
	paginator = Paginator(articles_list,5)
	page = request.GET.get('page')
	try:
		current_page = paginator.page(page)
		articles = current_page.object_list
	except PageNotAnInteger:
		current_page = paginator.page(1)
		articles = current_page.object_list
	except EmptyPage:
		current_page = paginator.page(paginator.num_pages)
		articles = current_page.object_list
	return render(request, "article/column/article_list.html", {"articles":articles, "page":current_page})

#显示话题正文视图
@login_required(login_url='/account/login')
def article_detail(request,id,slug):
	article = get_object_or_404(AriticlePost, id=id, slug=slug)
	return render(request, "article/column/article_detail.html", {"article":article})

#删除话题视图
@login_required(login_url='/account/login')
@require_POST   #这里表示只接受POST事件
@csrf_exempt
def del_article(request):
	article_id = request.POST['article_id']
	try:
		article = AriticlePost.objects.get(id=article_id)
		article.delete()
		#记录用户动作
		create_action(request.user, '删除了话题：', article)
		return HttpResponse("1")
	except Exception as e:
		return HttpResponse("2")

#编辑话题视图
@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request,article_id):
	if request.method == "GET":
		article_columns = request.user.article_column.all()
		article = AriticlePost.objects.get(id=article_id)
		this_article_form = AriticlePostForm(initial={"title":article.title})
		this_article_column = article_column
		return render(request, "article/column/redit_article.html", {"article":article, "article_columns":article_columns, "this_article_column":this_article_column, "this_article_form":this_article_form})

	else:
		redit_article = AriticlePost.objects.get(id=article_id)
		try:
			redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
			redit_article.title = request.POST['title']
			redit_article.body = request.POST['body']
			redit_article.save()
			#记录用户动作
			create_action(request.user, '修改了话题：', redit_article)
			return HttpResponse("1")
		except Exception as e:
			return HttpResponse("2")

#富文本编辑器图片上传处理
@login_required(login_url='/account/login')
@require_POST   #这里表示只接受POST事件
@csrf_exempt
def editor_image_upload(request):
	response_data = {}
	if request.method == "POST":
		upload_image_file = request.FILES.get('editormd-image-file')
		#print(upload_image_file.name,upload_image_file.size)
		#取文件的扩展名
		file_ext = os.path.splitext(upload_image_file.name)[1]
		new_upload_image_file = timezone.now().strftime('%Y%m%d%H%M%S') + file_ext
		#print(new_upload_image_file)
		if not upload_image_file:
			response_data['success'] = 0
			response_data['message'] = u'图片格式异常'
			return HttpResponse(json.dumps(response_data),content_type="application/json")
		else:
			if upload_image_file.size < 5242880 :
				#按年和按日期建立图片文件夹，文件夹不存在，会自动创建
				up_year = timezone.now().strftime('%Y')
				up_date = timezone.now().strftime('%m')+"-"+timezone.now().strftime('%d')
				#组装图片路径并上传图片至服务器
				img_url = default_storage.save("editor_images"+"/"+request.user.username+"/"+up_year+"/"+up_date+"/"+new_upload_image_file,ContentFile(upload_image_file.read()))
				# tmp_file = os.path.join(settings.MEDIA_ROOT,img_url).replace('\\','/')	  #调试信息
				# upload_image_file.save(os.path.join(settings.BASE_DIR,'static/editor_up_load/%Y/%m/%d',new_upload_image_file))
				# print(img_url)  #调试信息
				# print(tmp_file)  #调试信息
				response_data['success'] = 1
				response_data['message'] = u'上传成功'
				#这里非常重要，路径一定不能修改，否则无法正常显示图片
				response_data['url'] = '/static/image_upload/'+img_url
				#response_data = {'success':1,'message':"上传成功",'url':'http://www.thinkheh.cn'}  ----样例
				return HttpResponse(json.dumps(response_data),content_type="application/json")
			else:
				response_data['success'] = 0
				response_data['message'] = u'图片大小超过 5 Mb'
				return HttpResponse(json.dumps(response_data),content_type="application/json")

#问题标签视图函数
@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
	if request.method == "GET":
		article_tags = ArticleTag.objects.filter(author=request.user)
		article_tag_form = ArticleTagForm()
		return render(request, "article/tag/tag_list.html", {"article_tags":article_tags, "article_tag_form":article_tag_form})

	if request.method == "POST":
		#取得用户输入的tag名称
		tag_name = request.POST['tag']
		#从数据库中筛选与当前author_id、tag相同的记录
		tags = ArticleTag.objects.filter(author_id=request.user.id,tag=tag_name)
		#从数据库中筛选当前用户的所有tag
		tag_re = ArticleTag.objects.filter(author=request.user)

		#首先判断tag是否存在
		if tags:
			return HttpResponse('标签名称已存在，请重新更换标签名称！')
		#如果tag不存在，就判断用户的tag数量是否超过10个（含10个），超出则不允许再创建
		elif(tag_re.count()>=10):
			return HttpResponse('标签数量超过10个，无法再添加！')
		#如果前两个条件均不满足，则创建新tag
		else:
			#下面是创建tag的过程
			tag_post_form = ArticleTagForm(data=request.POST)
			print(tag_re)
			if tag_post_form.is_valid():
				print("表单验证通过！")
				try:
					new_tag = tag_post_form.save(commit=False)
					new_tag.author = request.user
					new_tag.save()
					return HttpResponse("1")
				except Exception as e:
					print(e)
					return HttpResponse("数据保存失败")
				else:
					return HttpResponse("对不起，表单验证失败！")

#删除话题标签视图
@login_required(login_url='/account/login')
@require_POST   #这里表示只接受POST事件
@csrf_exempt
def del_article_tag(request):
	tag_id = request.POST['tag_id']
	try:
		tag = ArticleTag.objects.get(id=tag_id)
		tag.delete()
		return HttpResponse("1")
	except Exception as e:
		print(e)
		return HttpResponse("2")

templates/article/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static '/css/normalize.css' %}">
</head>
<body style="padding: 80px">
	
	<div class="container">
		{% include "article/header.html" %}
		<div class="col-md-2">
		{% include "article/leftslider.html" %}
		</div>
		<div class="col-md-10">
		{% block content %}{% endblock content %}
		</div>
	</div>
{% include "footer.html" %}
<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/js/bootstrap.js' %}"></script>
</body>
</html>

templates/article/footer.html
<footer class="footer" style="padding: inherit;">
	<hr>
	<div class="container">
		<p>&copy; By warlock921 {% now "Y" %}</p>
	</div>
</footer>

templates/article/header.html
{% load staticfiles %}

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">导航</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav" role="navigation">
        <li><a class="navbar-brand" href="{% url 'mainsite:mainsite_title' %}">首页</a></li>
        <li><a class="navbar-brand" href="{% url 'article:article_list' %}">问答管理</a></li>
        <li><a class="navbar-brand" href="{% url 'imageload:list_images' %}">企业相册管理</a></li>
        {% if user.is_superuser %}
        <li><a class="navbar-brand" href="{% url 'course:manage_course' %}">视频新闻管理</a></li>
        {% endif %}
      </ul>
    </div>
    <div id="navbar" class="navbar-collapse collapse navbar-right">
      <div class="navbar-form navbar-right">
        {% if user.is_authenticated %}
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }} {% if user.is_superuser %}超级管理员{% endif %}<span class="caret"></span></button>
            <ul class="dropdown-menu">
              {% if user.is_superuser %}
               <li><a href="/admin">管理后台</a></li>
              {% endif %}
              <li><a href="{% url 'account:my_info' %}">信息中心</a></li>
              <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
              <li><a href="{% url 'account:password_reset' %}">忘记密码</a></li>
              <li><a href="{% url 'account:user_logout' %}">注销</a></li>
            </ul>
          </div>
        {% else %}
          <a href="{% url 'account:user_login' %}" class="btn btn-success" role="button">登录</a>
          <!-- <a href="{% url 'account:user_register' %}" class="btn btn-success" role="button">注册</a> -->
        {% endif %}
      </div>
    </div>
  </div>
</nav>
<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<!-- <script type="text/javascript" src="{% static '/js/bootstrap.js' %}"></script> -->

templates/article/leftslider.html
<div class="bg-info">
	<div class="text-center" style="margin-top: 20px">
		<h4>问答管理</h4>
		<p><a href="{% url 'article:article_column' %}">私有栏目</a></p>
		<p><a href="{% url 'article:article_post' %}">发起话题</a></p>
		<p><a href="{% url 'article:article_list' %}">话题列表</a></p>
		<p><a href="{% url 'article:article_tag' %}">话题标签</a></p>
	</div>
	<hr>
	<div div class="text-center" style="margin-top: 5px">
		<p><h4>企业相册管理</h4></p>
		<p><a href="{% url 'imageload:list_images' %}">企业相册管理</a></p>
	</div>
	{% if user.is_superuser %}
    <hr>
	<div div class="text-center" style="margin-top: 5px">
		<p><h4>企业视频新闻管理</h4></p>
		<p><a href="{% url 'course:manage_course' %}">企业视频新闻专题列表</a></p>
	</div>
    {% endif %}
</div>